/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Assignment;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Menu_Page extends javax.swing.JFrame {

    ImageIcon background= new ImageIcon("menu.png");
    ImageIcon logo= new ImageIcon("logo.png");
    ImageIcon notification= new ImageIcon("notifi.png");
    /** Creates new form Menu_Page */
    
    public Menu_Page() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        ID_input = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Pw_input = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LogIn2 = new javax.swing.JButton();
        registration = new javax.swing.JButton();
        Info = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jTextField1.setText("What sports do we provide? What's the price? Types of professional coaches?  CLICK NOW! ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorRemoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setText("jLabel1");
        Logo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LogoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 120));

        ID_input.setBackground(new java.awt.Color(204, 204, 255));
        ID_input.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ID_input.setForeground(new java.awt.Color(102, 255, 102));
        ID_input.setText("Enter Username");
        ID_input.setBorder(null);
        ID_input.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ID_inputAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ID_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ID_inputFocusGained(evt);
            }
        });
        ID_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_inputActionPerformed(evt);
            }
        });
        jPanel2.add(ID_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 268, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 40));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        Pw_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Pw_input.setForeground(new java.awt.Color(255, 255, 51));
        Pw_input.setText("jPasswordField1");
        Pw_input.setBorder(null);
        Pw_input.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Pw_inputAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Pw_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Pw_inputFocusGained(evt);
            }
        });
        Pw_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pw_inputActionPerformed(evt);
            }
        });
        jPanel2.add(Pw_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, 20));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 36));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Don't have an account? ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, 36));

        LogIn2.setBackground(new java.awt.Color(153, 255, 153));
        LogIn2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LogIn2.setForeground(new java.awt.Color(255, 255, 255));
        LogIn2.setText("Log In");
        LogIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn2ActionPerformed(evt);
            }
        });
        jPanel2.add(LogIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 120, 30));

        registration.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        registration.setForeground(new java.awt.Color(255, 255, 255));
        registration.setText("Register Here");
        registration.setBorder(null);
        registration.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                registrationAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        jPanel2.add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 270, 460));

        Info.setBackground(new java.awt.Color(255, 102, 102));
        Info.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        Info.setForeground(new java.awt.Color(0, 0, 0));
        Info.setBorder(null);
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });
        jPanel1.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 381, -1, 10));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 255));
        jButton2.setBorder(null);
        jButton2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 190, 150));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("About Us");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 80, 30));

        Background.setText("jLabel1");
        Background.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                BackgroundAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1AncestorAdded

    private void jPanel1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorRemoved

    private void BackgroundAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_BackgroundAncestorAdded
        // TODO add your handling code here:
        Background.setIcon(background);
    }//GEN-LAST:event_BackgroundAncestorAdded

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void LogoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LogoAncestorAdded
        // TODO add your handling code here:
        Logo.setIcon(logo);
    }//GEN-LAST:event_LogoAncestorAdded

    private void ID_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ID_inputFocusGained
        // TODO add your handling code here:
        ID_input.setText("");
    }//GEN-LAST:event_ID_inputFocusGained

    private void ID_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_inputActionPerformed

    private void Pw_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Pw_inputFocusGained
        // TODO add your handling code here:
        Pw_input.setText("");
    }//GEN-LAST:event_Pw_inputFocusGained

    private void Pw_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pw_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pw_inputActionPerformed

    private void LogIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn2ActionPerformed
        // TODO add your handling code here:
        boolean flag;
        Person person = new Person();
        person.set_id(ID_input.getText());
        person.set_password(Pw_input.getText());
        flag = person.login();
        if(flag){
            JOptionPane.showMessageDialog(null, "Logging in...");
            if(person.isStudent(person.get_id())){
                Registered_Students rs = new Registered_Students(person.get_id());
                rs.setVisible(true);
                this.setVisible(false);
            }else{
                Admin_Page am = new Admin_Page(person.get_id());
                am.setVisible(true);
                this.setVisible(false);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Wrong credential!");
        }                     
    }//GEN-LAST:event_LogIn2ActionPerformed

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        // TODO add your handling code here:
        Registration_1 r1= new Registration_1();
        r1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrationActionPerformed

    private void registrationAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_registrationAncestorAdded
        // TODO add your handling code here:
        registration.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
    }//GEN-LAST:event_registrationAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Select_sport_centre  r3 = new Select_sport_centre(1);
        r3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_InfoActionPerformed

    private void jButton2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton2AncestorAdded
        // TODO add your handling code here:
        jButton2.setIcon(notification);
    }//GEN-LAST:event_jButton2AncestorAdded

    private void ID_inputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ID_inputAncestorAdded
        // TODO add your handling code here:
        ID_input.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
    }//GEN-LAST:event_ID_inputAncestorAdded

    private void Pw_inputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Pw_inputAncestorAdded
        // TODO add your handling code here:
        Pw_input.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
    }//GEN-LAST:event_Pw_inputAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        About_Us us= new About_Us();
        us.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField ID_input;
    private javax.swing.JTextField Info;
    private javax.swing.JButton LogIn2;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField Pw_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton registration;
    // End of variables declaration//GEN-END:variables

}
