/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Registered_Students extends javax.swing.JFrame {

    /**
     * Creates new form Registered_Students
     */
    ImageIcon Logo= new ImageIcon("logo.png");
    ImageIcon background= new ImageIcon("student_background.png");
    ImageIcon home= new ImageIcon("home_button.png");
    ImageIcon coach= new ImageIcon("coach_icon.png");
    ImageIcon self= new ImageIcon("self_icon.png");
    ImageIcon sport= new ImageIcon("time_button.png");
    ImageIcon door= new ImageIcon("door_button.png");
    
    Students student = new Students();
    Coaches c = new Coaches();
    String[] array;
    
    public Registered_Students() {
        initComponents();
    }
    
    public Registered_Students(String id){
        initComponents();
        student.set_id(id);
        array = c.search_coach_by_stid(student.get_id());
        student.set_old_student_detail();
        student.set_old_password();
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Menu_Panel = new javax.swing.JPanel();
        home_button = new javax.swing.JButton();
        self_button = new javax.swing.JButton();
        logO_button = new javax.swing.JButton();
        coach_button = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        sport_button = new javax.swing.JButton();
        Main_Panel = new javax.swing.JPanel();
        Home_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Coach_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CID = new javax.swing.JLabel();
        CN = new javax.swing.JLabel();
        CDJ = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CHR = new javax.swing.JLabel();
        CDT = new javax.swing.JLabel();
        CPN = new javax.swing.JLabel();
        CBN = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CCC = new javax.swing.JLabel();
        rate1 = new javax.swing.JCheckBox();
        rate2 = new javax.swing.JCheckBox();
        rate3 = new javax.swing.JCheckBox();
        rate4 = new javax.swing.JCheckBox();
        rate5 = new javax.swing.JCheckBox();
        Self_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jPassword = new javax.swing.JTextField();
        jPN = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        ModifyBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        bNum = new javax.swing.JTextField();
        zCode = new javax.swing.JTextField();
        sName = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        stateName = new javax.swing.JTextField();
        countryName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Sports_Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Timetable = new javax.swing.JTable();
        student_background = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Panel.setBackground(new java.awt.Color(234, 134, 133));
        Menu_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Menu_Panel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Menu_PanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        home_button.setBackground(new java.awt.Color(102, 102, 255));
        home_button.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        home_button.setForeground(new java.awt.Color(0, 0, 0));
        home_button.setText("Home");
        home_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                home_buttonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });

        self_button.setBackground(new java.awt.Color(102, 102, 255));
        self_button.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        self_button.setForeground(new java.awt.Color(0, 0, 0));
        self_button.setText("Self-Record");
        self_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        self_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                self_buttonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        self_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                self_buttonActionPerformed(evt);
            }
        });

        logO_button.setBackground(new java.awt.Color(102, 102, 255));
        logO_button.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        logO_button.setForeground(new java.awt.Color(0, 0, 0));
        logO_button.setText("Log-Out");
        logO_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logO_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                logO_buttonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        logO_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logO_buttonActionPerformed(evt);
            }
        });

        coach_button.setBackground(new java.awt.Color(102, 102, 255));
        coach_button.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        coach_button.setForeground(new java.awt.Color(0, 0, 0));
        coach_button.setText("Coach");
        coach_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coach_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                coach_buttonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        coach_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coach_buttonActionPerformed(evt);
            }
        });

        logo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                logoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        sport_button.setBackground(new java.awt.Color(102, 102, 255));
        sport_button.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        sport_button.setForeground(new java.awt.Color(0, 0, 0));
        sport_button.setText("Sport-schedeule");
        sport_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sport_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sport_buttonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sport_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sport_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_PanelLayout = new javax.swing.GroupLayout(Menu_Panel);
        Menu_Panel.setLayout(Menu_PanelLayout);
        Menu_PanelLayout.setHorizontalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coach_button, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(home_button, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(self_button, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(logO_button, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(sport_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Menu_PanelLayout.setVerticalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(coach_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(self_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sport_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logO_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(Menu_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 470));

        Main_Panel.setBackground(new java.awt.Color(234, 134, 133));
        Main_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Main_Panel.setLayout(new java.awt.CardLayout());

        Home_Panel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME BACK !");

        javax.swing.GroupLayout Home_PanelLayout = new javax.swing.GroupLayout(Home_Panel);
        Home_Panel.setLayout(Home_PanelLayout);
        Home_PanelLayout.setHorizontalGroup(
            Home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_PanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Home_PanelLayout.setVerticalGroup(
            Home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_PanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        Main_Panel.add(Home_Panel, "card3");

        Coach_Panel.setBackground(new java.awt.Color(0, 51, 153));
        Coach_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Coach Information");
        Coach_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 233, 40));

        rate.setBackground(new java.awt.Color(255, 255, 255));
        rate.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        rate.setForeground(new java.awt.Color(255, 0, 0));
        rate.setText("Rate Your Coach Now !");
        rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateActionPerformed(evt);
            }
        });
        Coach_Panel.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");
        Coach_Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 40));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date Joined:");
        Coach_Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 40));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Name:");
        Coach_Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 40));

        CID.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CID.setForeground(new java.awt.Color(0, 0, 0));
        CID.setText("jLabel14");
        Coach_Panel.add(CID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        CN.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CN.setForeground(new java.awt.Color(0, 0, 0));
        CN.setText("jLabel15");
        Coach_Panel.add(CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        CDJ.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CDJ.setForeground(new java.awt.Color(0, 0, 0));
        CDJ.setText("jLabel16");
        CDJ.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CDJAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Coach_Panel.add(CDJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hourly Rate:");
        Coach_Panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 40));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Centre Name:");
        Coach_Panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, 40));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Date Terminated:");
        Coach_Panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 40));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phone Number:");
        Coach_Panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 40));

        CHR.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CHR.setForeground(new java.awt.Color(0, 0, 0));
        CHR.setText("jLabel16");
        Coach_Panel.add(CHR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        CDT.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CDT.setForeground(new java.awt.Color(0, 0, 0));
        CDT.setText("jLabel16");
        Coach_Panel.add(CDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        CPN.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CPN.setForeground(new java.awt.Color(0, 0, 0));
        CPN.setText("jLabel16");
        Coach_Panel.add(CPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        CBN.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CBN.setForeground(new java.awt.Color(0, 0, 0));
        CBN.setText("jLabel16");
        Coach_Panel.add(CBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Home Address:");
        Coach_Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 40));

        CCC.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CCC.setForeground(new java.awt.Color(0, 0, 0));
        CCC.setText("jLabel16");
        Coach_Panel.add(CCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        rate1.setText("1 star");
        rate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate1ActionPerformed(evt);
            }
        });
        Coach_Panel.add(rate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        rate2.setText("2 stars");
        rate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate2ActionPerformed(evt);
            }
        });
        Coach_Panel.add(rate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        rate3.setText("3 stars");
        rate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate3ActionPerformed(evt);
            }
        });
        Coach_Panel.add(rate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        rate4.setText("4 stars");
        rate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate4ActionPerformed(evt);
            }
        });
        Coach_Panel.add(rate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        rate5.setText("5 stars");
        rate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate5ActionPerformed(evt);
            }
        });
        Coach_Panel.add(rate5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        Main_Panel.add(Coach_Panel, "card3");

        Self_Panel.setBackground(new java.awt.Color(102, 153, 0));
        Self_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Self-Record");
        Self_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 6, 237, 40));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");
        Self_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");
        Self_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        jEmail.setBackground(new java.awt.Color(102, 153, 0));
        jEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jEmail.setForeground(new java.awt.Color(0, 0, 0));
        jEmail.setText("jTextField1");
        jEmail.setBorder(null);
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });
        Self_Panel.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, 30));

        jPassword.setBackground(new java.awt.Color(102, 153, 0));
        jPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPassword.setText("jTextField1");
        jPassword.setBorder(null);
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        Self_Panel.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 30));

        jPN.setBackground(new java.awt.Color(102, 153, 0));
        jPN.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPN.setForeground(new java.awt.Color(0, 0, 0));
        jPN.setText("jTextField1");
        jPN.setBorder(null);
        jPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPNActionPerformed(evt);
            }
        });
        Self_Panel.add(jPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 30));
        Self_Panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 130, 20));
        Self_Panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, 20));
        Self_Panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 20));

        ModifyBtn.setBackground(new java.awt.Color(255, 255, 255));
        ModifyBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ModifyBtn.setForeground(new java.awt.Color(255, 0, 0));
        ModifyBtn.setText("Modify");
        ModifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyBtnActionPerformed(evt);
            }
        });
        Self_Panel.add(ModifyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone Number:");
        Self_Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 40));

        bNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNumActionPerformed(evt);
            }
        });
        Self_Panel.add(bNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        Self_Panel.add(zCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        Self_Panel.add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));
        Self_Panel.add(tName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        Self_Panel.add(stateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));
        Self_Panel.add(countryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel5.setText("Building No");
        Self_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, -1));

        jLabel6.setText("Street Name");
        Self_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, -1));

        jLabel10.setText("Town Name");
        Self_Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jLabel20.setText("Zip");
        Self_Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, -1));
        Self_Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel22.setText("Country");
        Self_Panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel23.setText("State");
        Self_Panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        Main_Panel.add(Self_Panel, "card4");

        Sports_Panel.setBackground(new java.awt.Color(0, 153, 102));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your Sport-Schedule");

        Timetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Time Table"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Timetable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TimetableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(Timetable);

        javax.swing.GroupLayout Sports_PanelLayout = new javax.swing.GroupLayout(Sports_Panel);
        Sports_Panel.setLayout(Sports_PanelLayout);
        Sports_PanelLayout.setHorizontalGroup(
            Sports_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sports_PanelLayout.createSequentialGroup()
                .addGroup(Sports_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sports_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Sports_PanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        Sports_PanelLayout.setVerticalGroup(
            Sports_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sports_PanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        Main_Panel.add(Sports_Panel, "card5");

        jPanel1.add(Main_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 440, 470));

        student_background.setText("jLabel6");
        student_background.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                student_backgroundAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(student_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        // TODO add your handling code here:
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        Main_Panel.add(Home_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
        

    }//GEN-LAST:event_home_buttonActionPerformed

    private void self_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_self_buttonActionPerformed
        // TODO add your handling code here:
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        Main_Panel.add(Self_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
        student.getDetail(student.get_id());
        student.getPassword(student.get_id());
        jEmail.setText(student.get_email());
        jPassword.setText(student.get_password());
        jPN.setText(student.get_phone());
        String[] address = student.get_address();
        bNum.setText(address[0]);
        sName.setText(address[1]);
        tName.setText(address[2]);
        zCode.setText(address[3]);
        stateName.setText(address[4]);
        countryName.setText(address[5]);
    }//GEN-LAST:event_self_buttonActionPerformed

    private void logO_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logO_buttonActionPerformed
        // TODO add your handling code here:
        int dialogBtn=JOptionPane.YES_NO_OPTION;
        int dialogResult=JOptionPane.showConfirmDialog(this,"Confirm to Log-Out?","REMINDER",dialogBtn);
        
        if(dialogResult==0){
            Menu_Page main= new Menu_Page();
            main.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_logO_buttonActionPerformed

    private void coach_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coach_buttonActionPerformed
        // TODO add your handling code here:
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        Main_Panel.add(Coach_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
        CID.setText(array[0]);
        CN.setText(array[1]);
        CDJ.setText(array[2]);
        CDT.setText(array[3]);
        CHR.setText(array[4]);
        CPN.setText(array[5]);
        String address = array[6] + ", " + array[7] + ", " + array[8] + ", " + array[9] + ", " + array[10] + ", " + array[11]; 
        CBN.setText(address);
        CCC.setText(array[12]);
         
    }//GEN-LAST:event_coach_buttonActionPerformed

    private void logoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_logoAncestorAdded
        // TODO add your handling code here:
        logo.setIcon(Logo);
    }//GEN-LAST:event_logoAncestorAdded

    private void sport_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sport_buttonActionPerformed
        // TODO add your handling code here:
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        Main_Panel.add(Sports_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        DefaultTableModel time = (DefaultTableModel) Timetable.getModel();
            while (time.getRowCount() > 0) {
            time.removeRow(0);
            }
        Sports spt= new Sports();
        DefaultTableModel model = (DefaultTableModel)Timetable.getModel();
        String[] scheduleRow = spt.find_schedule(student.get_s_code());
        for(int i=0; i<scheduleRow.length;i++){
            String line = scheduleRow[i].toString().trim();
            model.addRow(new Object[]{line});
        }
    }//GEN-LAST:event_sport_buttonActionPerformed

    private void Menu_PanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Menu_PanelAncestorAdded
        // TODO add your handling code here:
        Menu_Panel.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
    }//GEN-LAST:event_Menu_PanelAncestorAdded

    private void student_backgroundAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_student_backgroundAncestorAdded
        // TODO add your handling code here:
        student_background.setIcon(background);
    }//GEN-LAST:event_student_backgroundAncestorAdded

    private void home_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_home_buttonAncestorAdded
        // TODO add your handling code here:
        home_button.setIcon(home);
    }//GEN-LAST:event_home_buttonAncestorAdded

    private void coach_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_coach_buttonAncestorAdded
        // TODO add your handling code here:
        coach_button.setIcon(coach);
    }//GEN-LAST:event_coach_buttonAncestorAdded

    private void self_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_self_buttonAncestorAdded
        // TODO add your handling code here:
        self_button.setIcon(self);
    }//GEN-LAST:event_self_buttonAncestorAdded

    private void sport_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sport_buttonAncestorAdded
        // TODO add your handling code here:
        sport_button.setIcon(sport);
    }//GEN-LAST:event_sport_buttonAncestorAdded

    private void logO_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_logO_buttonAncestorAdded
        // TODO add your handling code here:
        logO_button.setIcon(door);
    }//GEN-LAST:event_logO_buttonAncestorAdded

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPNActionPerformed

    private void rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateActionPerformed
        // TODO add your handling code here:
        try{
            if (rate1.isSelected()) {
                c.update_rating(1);
            } else if (rate2.isSelected()) {
                c.update_rating(2);
            } else if (rate3.isSelected()) {
                c.update_rating(3);
            } else if (rate4.isSelected()) {
                c.update_rating(4);
            } else {
                c.update_rating(5);
            }
        } catch (IOException iOException) {
        }
        JOptionPane.showMessageDialog(null, "Thank you for rating!");
    }//GEN-LAST:event_rateActionPerformed

    private void rate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate1ActionPerformed
        // TODO add your handling code here:
        if(rate1.isSelected()){
            rate2.setSelected(false);
            rate4.setSelected(false);
            rate5.setSelected(false);
            rate3.setSelected(false);
        }
    }//GEN-LAST:event_rate1ActionPerformed

    private void rate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate2ActionPerformed
        // TODO add your handling code here:
        if(rate2.isSelected()){
            rate1.setSelected(false);
            rate4.setSelected(false);
            rate5.setSelected(false);
            rate3.setSelected(false);
        }        
    }//GEN-LAST:event_rate2ActionPerformed

    private void rate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate3ActionPerformed
        // TODO add your handling code here:
        if(rate3.isSelected()){
            rate1.setSelected(false);
            rate4.setSelected(false);
            rate5.setSelected(false);
            rate2.setSelected(false);
        }    
    }//GEN-LAST:event_rate3ActionPerformed

    private void rate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate4ActionPerformed
        // TODO add your handling code here:
        if(rate4.isSelected()){
            rate1.setSelected(false);
            rate2.setSelected(false);
            rate5.setSelected(false);
            rate3.setSelected(false);
        }    
    }//GEN-LAST:event_rate4ActionPerformed

    private void rate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate5ActionPerformed
        // TODO add your handling code here:
        if(rate5.isSelected()){
            rate1.setSelected(false);
            rate4.setSelected(false);
            rate2.setSelected(false);
            rate3.setSelected(false);
        }    
    }//GEN-LAST:event_rate5ActionPerformed

    private void CDJAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CDJAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CDJAncestorAdded

    private void bNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNumActionPerformed

    private void ModifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyBtnActionPerformed
        // TODO add your handling code here:
        String buildingNo, streetName,cityName, zipNo, statename, countryname;
        if(!jPN.getText().isEmpty()){
            student.set_phone(jPN.getText());
        }
        
        if(!jEmail.getText().isEmpty()){
            student.set_email(jEmail.getText());
        }
        
        if(!jPassword.getText().isEmpty()){
            student.set_password(jPassword.getText());
        }
        
        if(!bNum.getText().isEmpty()){
            buildingNo = bNum.getText();
           if(!sName.getText().isEmpty()){
                streetName = sName.getText();
                if(!tName.getText().isEmpty()){
                    cityName = tName.getText();
                    if(!zCode.getText().isEmpty()){
                        zipNo = zCode.getText();
                        if(!stateName.getText().isEmpty()){
                            statename = stateName.getText();
                            if(!countryName.getText().isEmpty()){
                                countryname = countryName.getText();
                                student.set_address(buildingNo,streetName,cityName,zipNo,statename,countryname);
                                try {
                                    student.update_student_detail();
                                    student.update_student_password();
                                } catch (IOException ex) {
                                    Logger.getLogger(Registered_Students.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                JOptionPane.showMessageDialog(null, "Modify successful");
                                student.set_old_student_detail();
                                student.set_old_password();
                            }else{
                                JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                            }  
                        }else{
                            JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                        }  
                    }else{
                        JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                    }  
                }else{
                    JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                }  
            }else{
                JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
            }  
        }else{
           if(sName.getText().isEmpty()){
                if(tName.getText().isEmpty()){
                    if(zCode.getText().isEmpty()){
                        if(stateName.getText().isEmpty()){
                            if(countryName.getText().isEmpty()){
                                try {
                                    student.update_student_detail();
                                    student.update_student_password();
                                } catch (IOException ex) {
                                    Logger.getLogger(Registered_Students.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                JOptionPane.showMessageDialog(null, "Modify successful");
                            }else{
                                JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                            }  
                        }else{
                            JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                        }  
                    }else{
                        JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                    }  
                }else{
                    JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
                }  
            }else{
                JOptionPane.showMessageDialog(null, "Please complete your updates for all address fields");
            }   
        }
    }//GEN-LAST:event_ModifyBtnActionPerformed

    private void TimetableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TimetableAncestorAdded
        // TODO add your handling code here:
//        try {
//            File file = new File("student.txt");
//            BufferedReader br = new BufferedReader(new FileReader(file));
//            DefaultTableModel model = (DefaultTableModel) Timetable.getModel();
//            Object[] lines = br.lines().toArray();
//            for (int i = 0; i < lines.length; i++) {
//                String[] row = lines[i].toString().split(",");
//                if(row[0].equals()){
//                    model.addRow(row);
//                }
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(Person.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_TimetableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registered_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registered_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registered_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registered_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registered_Students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CBN;
    private javax.swing.JLabel CCC;
    private javax.swing.JLabel CDJ;
    private javax.swing.JLabel CDT;
    private javax.swing.JLabel CHR;
    private javax.swing.JLabel CID;
    private javax.swing.JLabel CN;
    private javax.swing.JLabel CPN;
    private javax.swing.JPanel Coach_Panel;
    private javax.swing.JPanel Home_Panel;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Menu_Panel;
    private javax.swing.JButton ModifyBtn;
    private javax.swing.JPanel Self_Panel;
    private javax.swing.JPanel Sports_Panel;
    private javax.swing.JTable Timetable;
    private javax.swing.JTextField bNum;
    private javax.swing.JButton coach_button;
    private javax.swing.JTextField countryName;
    private javax.swing.JButton home_button;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPassword;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton logO_button;
    private javax.swing.JLabel logo;
    private javax.swing.JButton rate;
    private javax.swing.JCheckBox rate1;
    private javax.swing.JCheckBox rate2;
    private javax.swing.JCheckBox rate3;
    private javax.swing.JCheckBox rate4;
    private javax.swing.JCheckBox rate5;
    private javax.swing.JTextField sName;
    private javax.swing.JButton self_button;
    private javax.swing.JButton sport_button;
    private javax.swing.JTextField stateName;
    private javax.swing.JLabel student_background;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField zCode;
    // End of variables declaration//GEN-END:variables
}
