/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Assignment;
import javax.swing.ImageIcon;
import java.io.*;
import javax.swing.JOptionPane;
import java.util.regex.*;
import java.util.*;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author User
 */
public class Registration_1 extends javax.swing.JFrame {
    
 
    ImageIcon Registration= new ImageIcon("Regis1.png");
    boolean fName_valid=false, lName_valid=false, pN_valid=false, email_valid=false, pass_valid=false;
    /** Creates new form Registration_1 */
    public Registration_1() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        Pno = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Pw = new javax.swing.JLabel();
        Copw = new javax.swing.JLabel();
        Input_FN = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Input_Phone = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Input_Email = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Input_CoPassword = new javax.swing.JPasswordField();
        Input_Password = new javax.swing.JPasswordField();
        Next_page = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        fName_Valid = new javax.swing.JLabel();
        lName_Valid = new javax.swing.JLabel();
        PhoneN_Valid = new javax.swing.JLabel();
        Email_Valid = new javax.swing.JLabel();
        Pass_Match = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sign Up Here !");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Lname.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Lname.setForeground(new java.awt.Color(255, 255, 255));
        Lname.setText("Full Name");
        jPanel2.add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 36));

        Pno.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Pno.setForeground(new java.awt.Color(255, 255, 255));
        Pno.setText("Phone Number");
        jPanel2.add(Pno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Email.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 20));

        Pw.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Pw.setForeground(new java.awt.Color(255, 255, 255));
        Pw.setText("Password");
        jPanel2.add(Pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Copw.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Copw.setForeground(new java.awt.Color(255, 255, 255));
        Copw.setText("Confirm Password");
        jPanel2.add(Copw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        Input_FN.setBackground(new java.awt.Color(153, 153, 255));
        Input_FN.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Input_FN.setForeground(new java.awt.Color(102, 102, 102));
        Input_FN.setText("Enter Full Name");
        Input_FN.setBorder(null);
        Input_FN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_FNFocusGained(evt);
            }
        });
        Input_FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_FNActionPerformed(evt);
            }
        });
        Input_FN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Input_FNKeyReleased(evt);
            }
        });
        jPanel2.add(Input_FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 268, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 260, 30));

        Input_Phone.setBackground(new java.awt.Color(153, 153, 255));
        Input_Phone.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Input_Phone.setForeground(new java.awt.Color(102, 102, 102));
        Input_Phone.setText("Enter Phone Number");
        Input_Phone.setBorder(null);
        Input_Phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_PhoneFocusGained(evt);
            }
        });
        Input_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_PhoneActionPerformed(evt);
            }
        });
        Input_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Input_PhoneKeyReleased(evt);
            }
        });
        jPanel2.add(Input_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 268, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 30));

        Input_Email.setBackground(new java.awt.Color(153, 153, 255));
        Input_Email.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Input_Email.setForeground(new java.awt.Color(102, 102, 102));
        Input_Email.setText("Enter Email");
        Input_Email.setBorder(null);
        Input_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_EmailFocusGained(evt);
            }
        });
        Input_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_EmailActionPerformed(evt);
            }
        });
        Input_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Input_EmailKeyReleased(evt);
            }
        });
        jPanel2.add(Input_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 268, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, 20));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, 30));

        Input_CoPassword.setBackground(new java.awt.Color(153, 153, 255));
        Input_CoPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Input_CoPassword.setForeground(new java.awt.Color(102, 102, 102));
        Input_CoPassword.setText("jPasswordField1");
        Input_CoPassword.setBorder(null);
        Input_CoPassword.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Input_CoPasswordAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Input_CoPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_CoPasswordFocusGained(evt);
            }
        });
        Input_CoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_CoPasswordActionPerformed(evt);
            }
        });
        Input_CoPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Input_CoPasswordKeyReleased(evt);
            }
        });
        jPanel2.add(Input_CoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 260, 30));

        Input_Password.setBackground(new java.awt.Color(153, 153, 255));
        Input_Password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Input_Password.setForeground(new java.awt.Color(102, 102, 102));
        Input_Password.setText("jPasswordField1");
        Input_Password.setBorder(null);
        Input_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_PasswordFocusGained(evt);
            }
        });
        Input_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(Input_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 260, 10));

        Next_page.setBackground(new java.awt.Color(51, 102, 255));
        Next_page.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Next_page.setForeground(new java.awt.Color(255, 255, 255));
        Next_page.setText("Next");
        Next_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_pageActionPerformed(evt);
            }
        });
        jPanel2.add(Next_page, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 120, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 260, 30));

        fName_Valid.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(fName_Valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, -1));

        lName_Valid.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(lName_Valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 20));

        PhoneN_Valid.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(PhoneN_Valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 20));

        Email_Valid.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(Email_Valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 260, 20));

        Pass_Match.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(Pass_Match, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 300, 460));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("I Run Because I Can");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 220, 100));

        RegPic.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        RegPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegPic.setText("jLabel1");
        RegPic.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                RegPicAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(RegPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 400, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_FNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_FNFocusGained
        // TODO add your handling code here:
        Input_FN.setText("");
    }//GEN-LAST:event_Input_FNFocusGained

    private void Input_FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_FNActionPerformed

    private void Input_PhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_PhoneFocusGained
        // TODO add your handling code here:
        Input_Phone.setText("");
    }//GEN-LAST:event_Input_PhoneFocusGained

    private void Input_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_PhoneActionPerformed

    private void Input_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_EmailFocusGained
        // TODO add your handling code here:
        Input_Email.setText("");
    }//GEN-LAST:event_Input_EmailFocusGained

    private void Input_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_EmailActionPerformed

    private void Input_CoPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_CoPasswordFocusGained
        // TODO add your handling code here:
        Input_CoPassword.setText("");
    }//GEN-LAST:event_Input_CoPasswordFocusGained

    private void Input_CoPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_CoPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_CoPasswordActionPerformed

    private void Input_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_PasswordFocusGained
        // TODO add your handling code here:
        Input_Password.setText("");
    }//GEN-LAST:event_Input_PasswordFocusGained

    private void Input_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_PasswordActionPerformed

    private void RegPicAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_RegPicAncestorAdded
        // TODO add your handling code here:
        RegPic.setIcon(Registration);
    }//GEN-LAST:event_RegPicAncestorAdded

    private void Next_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_pageActionPerformed
        // TODO add your handling code here:
        int count = 0;
        if(!Input_FN.getText().isEmpty()){
            count = count + 1;
        }
        if(!Input_Email.getText().isEmpty()){
            count = count + 1;
        }
        if(!Input_Phone.getText().isEmpty()){
            count = count + 1;
        }
        if(!Input_Password.getText().isEmpty()){
            count = count + 1;
        }
        if(!Input_CoPassword.getText().isEmpty()){
            count = count + 1;
        }
        if(count == 5){
            String main_pw = Input_Password.getText();
            String co_pw = Input_CoPassword.getText();
            if(main_pw.equals(co_pw)){
                Students student = new Students();   
                student.set_name(Input_FN.getText());
                student.set_email(Input_Email.getText());
                student.set_phone(Input_Phone.getText());
                student.set_password(main_pw);
                Registration_2 r2 = new Registration_2(student);
                r2.setVisible(true);
                this.setVisible(false);
            }
            else{
                showMessageDialog(null, "Password not match");
            }
        }else{
            showMessageDialog(null, "Please fill in all the fill before proceeding to the next page");
        }

    }//GEN-LAST:event_Next_pageActionPerformed

    private void Input_CoPasswordAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Input_CoPasswordAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_CoPasswordAncestorAdded

    private void Input_FNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Input_FNKeyReleased
        // TODO add your handling code here:
        String PATTERN= "(?i)[a-z]([- ',.a-z]{0,23}[a-z])?";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Input_FN.getText());
        if(!match.matches()){
            lName_Valid.setText("*Can only contain alphabet!");
            lName_valid=false;
        }
        else{
            lName_Valid.setText(null);
            lName_valid=true;
        }
    }//GEN-LAST:event_Input_FNKeyReleased

    private void Input_PhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Input_PhoneKeyReleased
        // TODO add your handling code here:
        String PATTERN= "^\\d{10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Input_Phone.getText());
        if(!match.matches()){
            PhoneN_Valid.setText("*Can only contain numbers!");
            pN_valid=false;
        }
        else{
            PhoneN_Valid.setText(null);
            pN_valid=true;
        }
        
      
    }//GEN-LAST:event_Input_PhoneKeyReleased

    private void Input_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Input_EmailKeyReleased
        // TODO add your handling code here:
        String PATTERN= "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Input_Email.getText());
        if(!match.matches()){
            Email_Valid.setText("*Email is invalid");
            email_valid=false;
        }
        else{
            Email_Valid.setText(null);
            email_valid=true;
        }
    }//GEN-LAST:event_Input_EmailKeyReleased

    private void Input_CoPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Input_CoPasswordKeyReleased
        // TODO add your handling code here:
        String checkPass=Input_Password.getText();
        if(!checkPass.equals(Input_CoPassword.getText())){
            Pass_Match.setText("*Password not matching!");
            pass_valid=false;
        }
        else{
            Pass_Match.setText("*Password Match!");
            pass_valid=true;
        }
    }//GEN-LAST:event_Input_CoPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copw;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email_Valid;
    private javax.swing.JPasswordField Input_CoPassword;
    private javax.swing.JTextField Input_Email;
    private javax.swing.JTextField Input_FN;
    private javax.swing.JPasswordField Input_Password;
    private javax.swing.JTextField Input_Phone;
    private javax.swing.JLabel Lname;
    private javax.swing.JButton Next_page;
    private javax.swing.JLabel Pass_Match;
    private javax.swing.JLabel PhoneN_Valid;
    private javax.swing.JLabel Pno;
    private javax.swing.JLabel Pw;
    private javax.swing.JLabel RegPic;
    private javax.swing.JLabel fName_Valid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lName_Valid;
    // End of variables declaration//GEN-END:variables

}