/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author tehyi
 */
public class Registration_2 extends javax.swing.JFrame {

    /**
     * Creates new form Registration_2
     */
    ImageIcon background= new ImageIcon("adressBack.png");
    Students student = new Students();
    
    public Registration_2() {
        initComponents();
    }
    
    public Registration_2(Students student){
        initComponents();
        this.student = student;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Next_pg = new javax.swing.JButton();
        Country = new javax.swing.JTextField();
        State = new javax.swing.JTextField();
        Zip = new javax.swing.JTextField();
        Town = new javax.swing.JTextField();
        Street = new javax.swing.JTextField();
        Building = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next_pg.setText("Next");
        Next_pg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_pgActionPerformed(evt);
            }
        });
        jPanel1.add(Next_pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });
        jPanel1.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 71, -1));
        jPanel1.add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 71, -1));

        Zip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipActionPerformed(evt);
            }
        });
        jPanel1.add(Zip, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 71, -1));

        Town.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TownActionPerformed(evt);
            }
        });
        jPanel1.add(Town, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 71, -1));

        Street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetActionPerformed(evt);
            }
        });
        jPanel1.add(Street, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 71, -1));

        Building.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingActionPerformed(evt);
            }
        });
        jPanel1.add(Building, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 71, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Enter Your Address");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 20));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Building No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Street");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("City");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Zip Code");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("State");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Country");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        back.setText("jLabel7");
        back.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                backAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 437, 319));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 437, 319));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Next_pgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_pgActionPerformed
        // TODO add your handling code here:
        int count = 0;
        if(!Building.getText().isEmpty()){
            count = count + 1;
        }
        if(!Street.getText().isEmpty()){
            count = count + 1;
        }
        if(!Town.getText().isEmpty()){
            count = count + 1;
        }
        if(!Zip.getText().isEmpty()){
            count = count + 1;
        }
        if(!State.getText().isEmpty()){
            count = count + 1;
        }
        if(!Country.getText().isEmpty()){
            count = count + 1;
        }
        if(count==6){
            student.set_address(Building.getText(), Street.getText(), Town.getText(), Zip.getText(), State.getText(), Country.getText());
            Select_sport_centre sss = new Select_sport_centre(student);
            sss.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Please complete all field before proceeding to the next page");
        }

    }//GEN-LAST:event_Next_pgActionPerformed

    private void ZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipActionPerformed

    private void TownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TownActionPerformed

    private void StreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetActionPerformed

    private void BuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildingActionPerformed

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryActionPerformed

    private void backAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_backAncestorAdded
        // TODO add your handling code here:
        back.setIcon(background);
    }//GEN-LAST:event_backAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Building;
    private javax.swing.JTextField Country;
    private javax.swing.JButton Next_pg;
    private javax.swing.JTextField State;
    private javax.swing.JTextField Street;
    private javax.swing.JTextField Town;
    private javax.swing.JTextField Zip;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
