/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment;

import javax.swing.ImageIcon;

/**
 *
 * @author tehyi
 */
public class Select_sport_centre extends javax.swing.JFrame {

    /**
     * Creates new form Registration_3
     */
    ImageIcon background= new ImageIcon("selectback.png");
    Sport_centres spctr = new Sport_centres();
    Students student = new Students();
    private int mode=0;
    
    public Select_sport_centre() {
        initComponents();
    }
    
    public Select_sport_centre(int mode) {
        initComponents();
        this.mode = mode;
        String[] array = spctr.readname_to_array();
        for(int i=0; i<array.length;i++){
           sport_centre_select.insertItemAt(array[i],i);
        }
    }
    
    public Select_sport_centre(Students student){
        initComponents();
        this.student=student;
        String[] array = spctr.readname_to_array();
        for(int i=0; i<array.length;i++){
           sport_centre_select.insertItemAt(array[i],i);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Next_pg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sport_centre_select = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next_pg.setText("Next");
        Next_pg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_pgActionPerformed(evt);
            }
        });
        jPanel1.add(Next_pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Select Your Sport Centre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        sport_centre_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sport_centre_selectActionPerformed(evt);
            }
        });
        jPanel1.add(sport_centre_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel2.setText("jLabel2");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Next_pgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_pgActionPerformed
        // TODO add your handling code here:
        String[] array1 = spctr.readid_to_array();
        int idx = sport_centre_select.getSelectedIndex();
        if(mode==0){
            student.set_c_code(array1[idx]);
            Select_sport ss = new Select_sport(student);
            ss.setVisible(true);
            this.setVisible(false);
        }else{
            Display_timetable dtt = new Display_timetable(array1[idx]);
            dtt.setVisible(true);
            this.setVisible(false);
        }  
    }//GEN-LAST:event_Next_pgActionPerformed

    private void sport_centre_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sport_centre_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sport_centre_selectActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
        jLabel2.setIcon(background);
    }//GEN-LAST:event_jLabel2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select_sport_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select_sport_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select_sport_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select_sport_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_sport_centre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next_pg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> sport_centre_select;
    // End of variables declaration//GEN-END:variables
}
