/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author tehyi
 */
public class Select_coach extends javax.swing.JFrame {

    /**
     * Creates new form Select_coach
     */
    ImageIcon background= new ImageIcon("coachback.png");
    Students student = new Students();
    Coaches coach = new Coaches();
    
    public Select_coach() {
        initComponents();
    }
    public Select_coach(Students student){
        initComponents();
        this.student = student;
        String[] array = coach.readname_to_array(student.get_c_code(), student.get_s_code());
        for(int i=0; i<array.length;i++){
           coach_select.insertItemAt(array[i],i);
        }     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coach_select = new javax.swing.JComboBox<>();
        Next_pg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hourly_text = new javax.swing.JTextField();
        rating_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coach_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coach_selectActionPerformed(evt);
            }
        });
        getContentPane().add(coach_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, -1));

        Next_pg.setText("Next");
        Next_pg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_pgActionPerformed(evt);
            }
        });
        getContentPane().add(Next_pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel1.setText("Please Select Your Coach");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
        getContentPane().add(hourly_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, -1));
        getContentPane().add(rating_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, -1));

        jLabel3.setText("Hourly Rate :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setText("Rating :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel2.setText("jLabel2");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Next_pgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_pgActionPerformed
        // TODO add your handling code here:
        String[] array1 = coach.readid_to_array(student.get_c_code(), student.get_s_code());
        if(coach_select.getSelectedItem()!=null){
            int idx = coach_select.getSelectedIndex();
            student.set_coach_id(array1[idx]);
            student.register();
            JOptionPane.showMessageDialog(null, "Register successful! Your User ID is : " + student.get_id() + ". Please use this ID to log in");
            Display_timetable dstt = new Display_timetable(student);
            dstt.setVisible(true);
            this.setVisible(false);
        }else{
            showMessageDialog(null, "Please fill select a coach before proceeding to the next page");
        }
    }//GEN-LAST:event_Next_pgActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
        jLabel2.setIcon(background);
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void coach_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coach_selectActionPerformed
        // TODO add your handling code here:
        String[] array1 = coach.readid_to_array(student.get_c_code(), student.get_s_code());
        int idx = coach_select.getSelectedIndex();
        String[] coach_array = coach.display_coach(array1[idx]);
        hourly_text.setText(coach_array[4]);
        rating_text.setText(coach_array[14]);
    }//GEN-LAST:event_coach_selectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select_coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select_coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select_coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select_coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_coach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next_pg;
    private javax.swing.JComboBox<String> coach_select;
    private javax.swing.JTextField hourly_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField rating_text;
    // End of variables declaration//GEN-END:variables
}
